name: snail
description: A library inspired by Spring Boot's JPA that facilitates SQLite database management in Flutter/Dart applications.
version: 1.1.3
homepage: https://github.com/evandersondev/snail

platforms:
  android:
  ios:
  macos:

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.3.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  sqflite: ">=1.1.2 <3.0.0"

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.12
